// Export pages
export '/pages/language_translator/translation_screen/translation_screen.dart'
    show TranslationScreenWidget;
export '/pages/medical_assistant/language_selection/language_selection.dart'
    show LanguageSelectionWidget;
export '/pages/medical_assistant/chat_screen/chat_screen.dart'
    show ChatScreenWidget;
export '/pages/home_screen/home_screen.dart' show HomeScreenWidget;
export '/pages/health_library/educational_content_home/educational_content_home.dart'
    show EducationalContentHomeWidget;
export '/pages/health_library/article_detail_screen/article_detail_screen.dart'
    show ArticleDetailScreenWidget;
export '/pages/vitals/vitals_monitor_screen/vitals_monitor_screen.dart'
    show VitalsMonitorScreenWidget;
export '/pages/registration_flow_screens/welcome_screen/welcome_screen.dart'
    show WelcomeScreenWidget;
export '/pages/registration_flow_screens/phone_auth_screen/phone_auth_screen.dart'
    show PhoneAuthScreenWidget;
export '/pages/registration_flow_screens/phone_verify_screen/phone_verify_screen.dart'
    show PhoneVerifyScreenWidget;
export '/pages/registration_flow_screens/registration_screen/registration_screen.dart'
    show RegistrationScreenWidget;
export '/pages/registration_flow_screens/medical_history_screen/medical_history_screen.dart'
    show MedicalHistoryScreenWidget;
export '/pages/registration_flow_screens/emergency_contacts_screen/emergency_contacts_screen.dart'
    show EmergencyContactsScreenWidget;
export '/pages/registration_flow_screens/registration_complete_screen/registration_complete_screen.dart'
    show RegistrationCompleteScreenWidget;
export '/pages/profile/profile_screen/profile_screen.dart'
    show ProfileScreenWidget;
export '/pages/profile/edit_profile_screen/edit_profile_screen.dart'
    show EditProfileScreenWidget;
export '/pages/doctor_comms/doctor_patient_chat/doctor_patient_chat.dart'
    show DoctorPatientChatWidget;
